# Project: testProj
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = Untitled.o formatOutput.o
LINKOBJ  = Untitled.o formatOutput.o
LIBS     = -L"D:/Devcpp/Dev-Cpp/MinGW64/lib" -L"D:/Devcpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/Devcpp/Dev-Cpp/MinGW64/include" -I"D:/Devcpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Devcpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Devcpp/Dev-Cpp/MinGW64/include" -I"D:/Devcpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Devcpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Devcpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = testProj.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Untitled.o: Untitled.cpp
	$(CPP) -c Untitled.cpp -o Untitled.o $(CXXFLAGS)

formatOutput.o: formatOutput.cpp
	$(CPP) -c formatOutput.cpp -o formatOutput.o $(CXXFLAGS)
